### PR TITLE
Create pybitmessage.profile

### PR DESCRIPTION
**Pull request by 1dnrr**
tested on fedora-28 with pybitmessage 0.6.3.2

### CODE REVIEW

**Comment by chiraag-nataraj** [comment]
Please rewrite using `common.inc`. That's what the file is there for!

**Comment by 1dnrr** [comment]
I do not exactly understand what it means using common.inc file. I'm afraid of wasting time on useless work. I also made a request to the firejail repository. I'm waiting for a time, and I'll make changes if needed.

**Comment by chiraag-nataraj** [comment]
@1dnrr Please take a look at the other profiles in this repo to see what I mean with respect to `common.inc` (it's a file in the repo).

**Comment by chiraag-nataraj** [comment]
Longer explanation:

The framework in this repo is very different from the main firejail profiles. Most of the profiles now use `common.inc` as a starting point, which disables many things by default. Often, it's "too strict", so you use `ignore` statements until the program works. Then, you add program-specific whitelists for the home directory, `private-bin`, `private-etc`, and possibly `private-lib` and whitelisting files in `/usr/share`. Using `common.inc` allows me to make a change in all profiles at once, which is useful when a new option lands. The profiles in this repo don't use the `whitelist-*` files or `disable-` files that come with standard firejail.

**Comment by chiraag-nataraj** [comment]
@1dnrr I'm going to go ahead and reject this since your profile was accepted by upstream firejail. If you want to submit a more restrictive profile to this repo, please look at some of the other profiles in the repo to get an idea of what I mean.

**Pull request closed without merging**
