### PR TITLE
Adding the Quodlibet music player

### PR DESCRIPTION
**Pull request by Bundy01**

### CODE REVIEW

**Comment by Bundy01** [comment]
Sorry, I went too fast for the first PR.
Renaming 'quodlibet' to 'quodlibet.profile'.

**Comment by chiraag-nataraj** [comment]
@Bundy01, can you please try using `common.inc` (as is used in other profiles)? That way, it will resemble the other profiles in the repo. Thanks!

**Comment by Bundy01** [comment]
Hi,
I don't have the common file in my home. Is it due to the version of firejail I use: **firejail version 0.9.58.2**
Or is there something to be done?

**Comment by chiraag-nataraj** [comment]
It doesn't come with `firejail` - it's the `common.inc` file in this repository.

**Comment by chiraag-nataraj** [comment]
Merged, thanks!

**Pull request merged**
